### ISSUE TITLE
"Final Marker slowness amplifier" in config actually amplifies strength

### ISSUE THREAD

**Issue by Similacrest** [AnOpenSauceDev/Weight#3]
https://github.com/AnOpenSauceDev/Weight/blob/master/src/main/java/an/opensauce/armourweight/mixin/PlayerEntityMixin.java#L56
`            player.addStatusEffect(new StatusEffectInstance(StatusEffects.STRENGTH,(10*20),amp,!false,false,false));`

Not sure if intentional

**Comment by AnOpenSauceDev** [comment]
at the time my reasoning was that the slowness vs strength would make people use heavy gear more often, but in hindsight i probably should've halved, then floored the value.

**Comment by Similacrest** [comment]
Sorry for not being clear enough. My issue was that amp for slowness does not actually amplify slowness, it's hardcoded as 2.

**Comment by AnOpenSauceDev** [comment]
> Sorry for not being clear enough. My issue was that amp for slowness does not actually amplify slowness, it's hardcoded as 2.

I'll fix that, didn't notice
