### ISSUE TITLE
Detect more modded armors

### ISSUE THREAD

**Issue by k1r0s** [AnOpenSauceDev/Weight#6]
would be nice to add keywords association, like see. Most of modded armors are named "$MATERIAL helmet" or "$MATERIAL chestplate"

![image](https://github.com/AnOpenSauceDev/Weight/assets/6052309/7aee16c8-f0a4-43ee-9b5f-59e59175d23e)

Would be nice to declare in the configuration like this.

"$MATERIAL": "$WEIGHT" // weight being a number from 0 to 10 being 10 netherite like and 0 no weight penality

**Comment by AnOpenSauceDev** [comment]
There is already two systems built-in to calculate weight:
1. The fallback calculator, which just takes in a few of the characteristics and spits out a weight value.
2. The datapack system, where you can just make a few definitions and upload them to your server/modrinth

If the first system isn't working well for you, just make a datapack and define everything you need there.
