### ISSUE TITLE
how do i remove resistance and strength from diamond and netherite

### ISSUE THREAD

**Issue by Zanjitku** [AnOpenSauceDev/Weight#8]
I'm not sure if this is the right place to ask, but I was wondering how to remove the strength and resistance bonuses at certain weights? I couldn't figure it out myself.

**Comment by AnOpenSauceDev** [comment]
Sorry for the late reply! Here's what you can do:

You can go into the config and change **"Marker 3 Amplifier"** and **"Marker 2 Amplifier"** to any lower value you want.

A quick breakdown is:

Amplifier = 1: Slowness.

Amplifier = 2: (Slowness * amplifier) + Resistance.

Amplifier = 3: (Slowness * amplifier) + Resistance 2 + Strength.

Depending on the question you have, some mod developers might prefer you to use [Discussions](https://github.com/AnOpenSauceDev/Weight/discussions), but an Issue is normally fine.

**Comment by Zanjitku** [comment]
thanks for the help, I appreciate it.

**Comment by AnOpenSauceDev** [comment]
No Problem!
