### ISSUE TITLE
Instant feedback when swapping armor

### ISSUE THREAD

**Issue by duarm** [AnOpenSauceDev/Weight#9]
Amazing mod, good work!

### Problem
While experimenting with a bunch of armors trying to find a good combination, I noticed the weight feedback is not instant, if you're wearing full diamond with Slowness 3, If you swap to an iron set which is Slowness 1 weight, you need to wait for the previous Slowness 3 to wear off in order for it to represent the weight of the armor you're actually wearing.

### Expectation

Update the slowness debuff when you swap/equip/unequip the armor.

**Comment by AnOpenSauceDev** [comment]
Now fixed in https://github.com/AnOpenSauceDev/Weight/commit/f3624d3ba6e639e1dd37c25a72d8ddf92a6334bf.
